# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=30)),
                ('rankPos', models.IntegerField()),
                ('recentMatch', models.ManyToManyField(to='optItem.Match')),
            ],
            options={
                'ordering': ('rankPos',),
            },
        ),
    ]
