# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0003_auto_20170504_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('itemid',)},
        ),
    ]
