# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0005_auto_20170504_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='champPlayed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numChampionPlayed', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optItem.Champion')),
            ],
        ),
    ]
