# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0006_champplayed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summoner',
            options={'ordering': ('-rankPos',)},
        ),
    ]
