# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0007_auto_20170519_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='actid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
