# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0008_summoner_actid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summoner',
            options={'ordering': ('-leaguePoints',)},
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='rankPos',
            new_name='leaguePoints',
        ),
    ]
