# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0009_auto_20170523_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='dateCreated',
            field=models.DateTimeField(null=True),
        ),
    ]
