# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0010_match_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='champ1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ10',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ10ItemList',
            field=models.ManyToManyField(related_name='champ10_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ10Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ10lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ1ItemList',
            field=models.ManyToManyField(related_name='champ1_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ1Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ1lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ2ItemList',
            field=models.ManyToManyField(related_name='champ2_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ2Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ2lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ3ItemList',
            field=models.ManyToManyField(related_name='champ3_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ3Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ3lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ4ItemList',
            field=models.ManyToManyField(related_name='champ4_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ4Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ4lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ5ItemList',
            field=models.ManyToManyField(related_name='champ5_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ5Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ5lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ6',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ6ItemList',
            field=models.ManyToManyField(related_name='champ6_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ6Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ6lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ7',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ7ItemList',
            field=models.ManyToManyField(related_name='champ7_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ7Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ7lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ8',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ8ItemList',
            field=models.ManyToManyField(related_name='champ8_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ8Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ8lane',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='match',
            name='champ9',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='champ9ItemList',
            field=models.ManyToManyField(related_name='champ9_itemlist', to='optItem.Item'),
        ),
        migrations.AddField(
            model_name='match',
            name='champ9Win',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='match',
            name='champ9lane',
            field=models.CharField(default='', max_length=30),
        ),
    ]
