# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optItem', '0011_auto_20170711_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gameVersion',
            field=models.CharField(default='', max_length=50),
        ),
    ]
